apiVersion: v1
kind: Service
metadata:
  name: nk-service
  namespace: nk-namespace
  labels:
    app: nk-app
spec:
  selector:
    app: nk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nk-deployment
  namespace: nk-namespace
  labels:
    app: nk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nk-app
  template:
    metadata:
      labels:
        app: nk-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/z9d2n7e1/nginx:1.19.5
        ports:
        - containerPort: 80